"""Sanity checks for the hand-maintained dist/service-worker.js.

This file is not generated by the Python pipeline (it's a tracked static
asset -- see the ``!dist/service-worker.js`` exception in .gitignore), so
these are lightweight text-based checks rather than execution tests.
"""

from __future__ import annotations

from pathlib import Path

from core.asset_utils import CDN_TO_VENDOR, LEAFLET_VENDOR_IMAGE_PATHS

_SW_PATH = Path(__file__).resolve().parent.parent / "dist" / "service-worker.js"


def _read_sw() -> str:
    return _SW_PATH.read_text(encoding="utf-8")


def test_service_worker_exists() -> None:
    assert _SW_PATH.is_file()


def test_cache_names_are_versioned_and_consistent() -> None:
    text = _read_sw()
    assert "CACHE_NAME" in text
    assert "IMAGE_CACHE" in text
    assert "VENDOR_CACHE" in text
    # activate handler must reference a single source of truth for "current"
    # caches so bumping a version can't accidentally leave a stale cache alive.
    assert "CURRENT_CACHES" in text


def test_every_vendor_asset_is_precached() -> None:
    """Every self-hosted CDN replacement path should be in VENDOR_ASSETS."""
    text = _read_sw()
    vendor_paths = (*CDN_TO_VENDOR.values(), *LEAFLET_VENDOR_IMAGE_PATHS)
    for vendor_path in vendor_paths:
        # asset_utils paths are root-relative (e.g. "/shared/vendor/x.js");
        # the service worker precache list uses the same paths without the
        # leading slash (relative to the site root where it's registered).
        relative_path = vendor_path.lstrip("/")
        assert relative_path in text, f"{relative_path} missing from VENDOR_ASSETS"


def test_json_sidecars_use_stale_while_revalidate() -> None:
    text = _read_sw()
    assert '.endsWith(".json")' in text


def test_vendor_assets_served_cache_first() -> None:
    text = _read_sw()
    assert "/shared/vendor/" in text
