"""Core shared utilities for the mapping pipeline.

Re-exports all public symbols so callers can use ``from core import ...``.
"""

from core.config import (
    DIST_DIR,
    AppConfig,
    get_config,
    get_favicon_html,
    get_google_analytics_script,
    get_service_worker_registration_script,
    get_twitter_card_meta,
    set_config,
    setup_logging,
)
from core.http import AntiBotDetectedError, get_headers, get_session, make_request, print_block
from core.types import (
    AddressLeague,
    AddressTeam,
    Fixture,
    FixtureLeague,
    GeocodedLeague,
    GeocodedTeam,
    GeocodeResult,
    League,
    LeagueInfo,
    LeagueTravelDistances,
    MapTeam,
    Team,
    TeamTravelDistances,
    TravelDistances,
    json_load_cache,
    sanitize_team_name,
    team_name_to_filepath,
)

__all__ = [
    "DIST_DIR",
    "AddressLeague",
    "AddressTeam",
    "AntiBotDetectedError",
    "AppConfig",
    "Fixture",
    "FixtureLeague",
    "GeocodedLeague",
    "GeocodedTeam",
    "GeocodeResult",
    "League",
    "LeagueInfo",
    "LeagueTravelDistances",
    "MapTeam",
    "Team",
    "TeamTravelDistances",
    "TravelDistances",
    "get_config",
    "get_favicon_html",
    "get_google_analytics_script",
    "get_service_worker_registration_script",
    "get_twitter_card_meta",
    "get_headers",
    "get_session",
    "json_load_cache",
    "make_request",
    "print_block",
    "sanitize_team_name",
    "set_config",
    "setup_logging",
    "team_name_to_filepath",
]
